/// Core data model for one flagged email.
///
/// Architecture: architecture.md §5.1
/// DB table: `mail_items` (column mapping in [MailItem.toMap])
library;

import 'dart:convert';

/// Where the spoken summary for this item comes from.
enum AudioSource {
  /// mp3 generated by ElevenLabs and saved on device.
  elevenlabs,

  /// No audio file — spoken on demand by flutter_tts when ▶ is tapped.
  offlineTts,

  /// Nothing to play yet (not processed).
  none;

  static AudioSource fromDb(String? value) {
    return switch (value) {
      'elevenlabs' => AudioSource.elevenlabs,
      'offline_tts' => AudioSource.offlineTts,
      _ => AudioSource.none,
    };
  }

  String get dbValue => switch (this) {
        AudioSource.elevenlabs => 'elevenlabs',
        AudioSource.offlineTts => 'offline_tts',
        AudioSource.none => 'none',
      };
}

/// Lifecycle of an item as far as the user is concerned.
enum ItemStatus {
  fresh,
  done,
  dismissed;

  static ItemStatus fromDb(String? value) {
    return switch (value) {
      'done' => ItemStatus.done,
      'dismissed' => ItemStatus.dismissed,
      _ => ItemStatus.fresh,
    };
  }

  String get dbValue => name;
}

class MailItem {
  /// Stable across sessions: `"${uid}_INBOX"`.
  final String id;
  final DateTime receivedAt;
  final String senderName;
  final String senderAddress;

  /// Stored locally only — NEVER sent to any API (prd.md §8).
  final String subject;

  /// Rules engine output. Gemma has no influence on this.
  final int score;

  /// Why this was flagged (debug/log only).
  final List<String> reasons;

  /// Extracted by the rules engine via regex. Null if none.
  /// Gemma must never invent this (rules.md §1).
  final DateTime? deadline;
  final bool isVip;

  // --- Gemma output. Null until the item has been processed. ---
  String? what;
  String? doIt;

  /// Human-readable deadline text ("Friday", "Oct 10"), or null.
  /// Mirrors the `by` field in architecture.md §5.1; persisted as `by_text`.
  String? by;

  /// what + ". " + doIt + (by != null ? " By " + by : "")
  String? speechText;

  // --- Audio ---
  String? audioPath;
  AudioSource audioSource;

  ItemStatus status;
  DateTime processedAt;

  MailItem({
    required this.id,
    required this.receivedAt,
    required this.senderName,
    required this.senderAddress,
    required this.subject,
    required this.score,
    required this.reasons,
    required this.deadline,
    required this.isVip,
    required this.processedAt,
    this.what,
    this.doIt,
    this.by,
    this.speechText,
    this.audioPath,
    this.audioSource = AudioSource.none,
    this.status = ItemStatus.fresh,
  });

  /// True once Gemma (or the fallback template) has produced WHAT/DO/BY.
  /// The widget only ever shows fully processed items (architecture.md §8).
  bool get isProcessed => what != null && doIt != null && speechText != null;

  /// True when the deadline has arrived or passed (drives the urgent style,
  /// prd.md §3.3). Comparison is date-only — a deadline later today is not
  /// yet urgent for the purposes of "is it still actionable".
  bool get isUrgent {
    final d = deadline;
    if (d == null) return false;
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final day = DateTime(d.year, d.month, d.day);
    return !day.isAfter(today);
  }

  MailItem copyWith({
    String? what,
    String? doIt,
    String? by,
    String? speechText,
    String? audioPath,
    AudioSource? audioSource,
    ItemStatus? status,
  }) {
    return MailItem(
      id: id,
      receivedAt: receivedAt,
      senderName: senderName,
      senderAddress: senderAddress,
      subject: subject,
      score: score,
      reasons: reasons,
      deadline: deadline,
      isVip: isVip,
      processedAt: processedAt,
      what: what ?? this.what,
      doIt: doIt ?? this.doIt,
      by: by ?? this.by,
      speechText: speechText ?? this.speechText,
      audioPath: audioPath ?? this.audioPath,
      audioSource: audioSource ?? this.audioSource,
      status: status ?? this.status,
    );
  }

  /// Row for the `mail_items` table (architecture.md §5.1).
  Map<String, Object?> toMap() => {
        'id': id,
        'received_at': receivedAt.millisecondsSinceEpoch,
        'sender_name': senderName,
        'sender_address': senderAddress,
        'subject': subject,
        'score': score,
        'reasons': jsonEncode(reasons),
        'deadline': deadline?.millisecondsSinceEpoch,
        'is_vip': isVip ? 1 : 0,
        'what': what,
        'do_it': doIt,
        'by_text': by,
        'speech_text': speechText,
        'audio_path': audioPath,
        'audio_source': audioSource.dbValue,
        'status': status.dbValue,
        'processed_at': processedAt.millisecondsSinceEpoch,
      };

  factory MailItem.fromMap(Map<String, Object?> map) {
    return MailItem(
      id: map['id'] as String,
      receivedAt: DateTime.fromMillisecondsSinceEpoch(map['received_at'] as int),
      senderName: (map['sender_name'] as String?) ?? '',
      senderAddress: (map['sender_address'] as String?) ?? '',
      subject: (map['subject'] as String?) ?? '',
      score: (map['score'] as int?) ?? 0,
      reasons: _decodeReasons(map['reasons']),
      deadline: _decodeDate(map['deadline']),
      isVip: ((map['is_vip'] as int?) ?? 0) == 1,
      what: map['what'] as String?,
      doIt: map['do_it'] as String?,
      by: map['by_text'] as String?,
      speechText: map['speech_text'] as String?,
      audioPath: map['audio_path'] as String?,
      audioSource: AudioSource.fromDb(map['audio_source'] as String?),
      status: ItemStatus.fromDb(map['status'] as String?),
      processedAt: DateTime.fromMillisecondsSinceEpoch(
          (map['processed_at'] as int?) ?? 0),
    );
  }

  static List<String> _decodeReasons(Object? raw) {
    if (raw is! String || raw.isEmpty) return const [];
    try {
      final decoded = jsonDecode(raw);
      if (decoded is List) return decoded.map((e) => e.toString()).toList();
    } on FormatException {
      // Corrupt row — treat as no reasons rather than failing the whole load.
    }
    return const [];
  }

  static DateTime? _decodeDate(Object? raw) {
    if (raw is int) return DateTime.fromMillisecondsSinceEpoch(raw);
    return null;
  }

  @override
  String toString() =>
      'MailItem($id, score=$score, what=$what, doIt=$doIt, by=$by)';
}